### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by r4f4** [modularity-modules/nginx#1]
The module includes gperftools, which is already included in shared-userspace.

**Comment by asamalik** [comment]
thanks! let me dump it

**Comment by asamalik** [comment]
waiting for a rebuild https://mbs.fedoraproject.org//module-build-service/1/module-builds/644

**Comment by asamalik** [comment]
resubmitted the build https://mbs.fedoraproject.org//module-build-service/1/module-builds/669

the build has succeeded, so this issue is fixed

**Comment by r4f4** [comment]
Thank you for the fix.
